# Generated by Django 5.1.4 on 2025-01-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(default=0)),
                ('priorty', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='media/')),
                ('delete_status', models.IntegerField(choices=[(1, 'live'), (0, 'delete')], default=1)),
            ],
        ),
    ]
