# Generated by Django 5.1.4 on 2025-01-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='orederstatus',
        ),
        migrations.AddField(
            model_name='cart',
            name='orderstatus',
            field=models.IntegerField(choices=[(1, 'ORDER_PROCESSED'), (2, 'DELIVERED'), (3, 'REJECTED'), (4, 'ORDER_CONFORMED')], default=0),
        ),
    ]
