# Generated by Django 5.1.4 on 2025-01-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_cart_orederstatus_cart_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orderstatus',
            field=models.IntegerField(choices=[(1, 'Oroder Processed'), (2, 'DELIVERED'), (3, 'REJECTED'), (4, 'ORDER_CONFORMED')], default=0),
        ),
    ]
