# Generated by Django 5.1.4 on 2025-01-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delete_status',
        ),
    ]
