# Generated by Django 5.1.4 on 2025-01-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=models.IntegerField(default=9999999999),
        ),
    ]
