# Generated by Django 5.1.4 on 2025-01-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.IntegerField(choices=[(1, 'Order Processed'), (2, 'Delivered'), (3, 'Rejected'), (4, 'Order Confirmed')], default=0),
        ),
    ]
